---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: hermesagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermesagent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hermesagent
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: hermesagent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: hermesagent-config
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          readinessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/status
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: hermes-home
              mountPath: /opt/data
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: hermes-home
          hostPath:
            {{- if .Values.sysVersion }}
              {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: "{{ .Values.userspace.appData }}/hermes-home"
              {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/hermes-home"
              {{- end }}
            {{- else }}
            path: "{{ .Values.userspace.appData }}/{{ .Release.Name }}/hermes-home"
            {{- end }}
            type: DirectoryOrCreate
